apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumora.fullname" . }}
  labels: {{- include "lumora.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector: {{- include "lumora.selectorLabels" . | nindent 4 }}
